#! /bin/sh

## AUTO START
~/.config/polybar/launch.sh --cuts  &
sxhkd &

feh --bg-fill ~/Wallpapers/material.png
picom --no-fading-openclose &


## MONITORS
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

## RULES

# Drop Down apps

bspc rule -a Xfce4-terminal state=floating

# Regular rules

bspc rule -a Steam desktop=^6 follow=off focus=off state=floating

bspc rule -a discord desktop=^5 follow=off focus=off

bspc rule -a csgo desktop=^3 focus=on

## BSPWM CONFIGURATION

bspc config border_width	1 

bspc config window_gap		0 

bspc config focused_border_color "#404040"
bspc config normal_border_color "#000000"

bspc config pointer_motion_interval 7ms


#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true





